set(_CATKIN_CURRENT_PACKAGE "myhand_sci_msgs")
set(myhand_sci_msgs_VERSION "0.1.0")
set(myhand_sci_msgs_MAINTAINER "Joaquin Palacios <jbp2157@columbia.edu>")
set(myhand_sci_msgs_PACKAGE_FORMAT "2")
set(myhand_sci_msgs_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(myhand_sci_msgs_BUILD_EXPORT_DEPENDS )
set(myhand_sci_msgs_BUILDTOOL_DEPENDS "catkin")
set(myhand_sci_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(myhand_sci_msgs_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(myhand_sci_msgs_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(myhand_sci_msgs_TEST_DEPENDS )
set(myhand_sci_msgs_DOC_DEPENDS )
set(myhand_sci_msgs_URL_WEBSITE "")
set(myhand_sci_msgs_URL_BUGTRACKER "")
set(myhand_sci_msgs_URL_REPOSITORY "")
set(myhand_sci_msgs_DEPRECATED "")